-- Agregar preguntas adicionales para completar evaluación OCEAN de 120+ preguntas
-- Completar Apertura a la Experiencia (25 preguntas total)
INSERT INTO public.personality_questions (question_text, ocean_factor, score_orientation, order_index) VALUES
-- Apertura - facetas: Fantasía, Estética, Sentimientos, Acciones, Ideas, Valores
('Tengo una imaginación muy activa', 'apertura', 'positive', 32),
('Me atraen las formas de arte abstracto', 'apertura', 'positive', 33),
('Disfruto explorando mis propios sentimientos', 'apertura', 'positive', 34),
('Me gusta probar comidas de diferentes culturas', 'apertura', 'positive', 35),
('Cuestiono las autoridades tradicionales', 'apertura', 'positive', 36),
('Prefiero las películas predecibles', 'apertura', 'negative', 37),
('Me gusta soñar despierto', 'apertura', 'positive', 38),
('La música me emociona profundamente', 'apertura', 'positive', 39),
('Reconozco mis estados emocionales fácilmente', 'apertura', 'positive', 40),
('Me gusta viajar a lugares desconocidos', 'apertura', 'positive', 41),
('Disfruto de debates intelectuales', 'apertura', 'positive', 42),
('Cuestiono los valores tradicionales de mi familia', 'apertura', 'positive', 43),
('Evito situaciones ambiguas', 'apertura', 'negative', 44),
('Me fascina la poesía', 'apertura', 'positive', 45),
('Presto atención a mis reacciones emocionales', 'apertura', 'positive', 46),
('Me gusta experimentar con estilos de vestimenta diferentes', 'apertura', 'positive', 47),
('Tengo curiosidad por teorías abstractas', 'apertura', 'positive', 48),
('Respeto las tradiciones establecidas', 'apertura', 'negative', 49),
('Tengo sueños vívidos y los recuerdo', 'apertura', 'positive', 50),
('Me conmueven las obras de arte', 'apertura', 'positive', 51),
('Reflexiono sobre mis motivaciones internas', 'apertura', 'positive', 52),
('Me gusta probar actividades físicas nuevas', 'apertura', 'positive', 53),
('Disfruto aprendiendo sobre filosofía', 'apertura', 'positive', 54),
('Prefiero seguir las normas sociales establecidas', 'apertura', 'negative', 55),
('Me intrigan los misterios sin resolver', 'apertura', 'positive', 56);

-- Completar Conciencia/Responsabilidad (25 preguntas total)
INSERT INTO public.personality_questions (question_text, ocean_factor, score_orientation, order_index) VALUES
-- Conciencia - facetas: Competencia, Orden, Sentido del deber, Lucha por el logro, Autodisciplina, Deliberación
('Termino los proyectos antes de la fecha límite', 'responsabilidad', 'positive', 57),
('Mi escritorio está siempre organizado', 'responsabilidad', 'positive', 58),
('Cumplo mis promesas sin excepción', 'responsabilidad', 'positive', 59),
('Me esfuerzo por alcanzar la excelencia', 'responsabilidad', 'positive', 60),
('Controlo mis impulsos efectivamente', 'responsabilidad', 'positive', 61),
('Reflexiono antes de tomar decisiones importantes', 'responsabilidad', 'positive', 62),
('A menudo llego tarde a las citas', 'responsabilidad', 'negative', 63),
('Pierdo cosas importantes frecuentemente', 'responsabilidad', 'negative', 64),
('Cancelo compromisos cuando no tengo ganas', 'responsabilidad', 'negative', 65),
('Me conformo con "suficientemente bueno"', 'responsabilidad', 'negative', 66),
('Cedo fácilmente a las tentaciones', 'responsabilidad', 'negative', 67),
('Tomo decisiones impulsivas', 'responsabilidad', 'negative', 68),
('Mantengo un horario regular', 'responsabilidad', 'positive', 69),
('Guardo recibos y documentos importantes', 'responsabilidad', 'positive', 70),
('Siento obligación moral de ayudar a otros', 'responsabilidad', 'positive', 71),
('Busco formas de mejorar mi desempeño', 'responsabilidad', 'positive', 72),
('Resisto distracciones cuando trabajo', 'responsabilidad', 'positive', 73),
('Considero las consecuencias antes de actuar', 'responsabilidad', 'positive', 74),
('Postergo tareas aburridas', 'responsabilidad', 'negative', 75),
('Mi casa está desordenada', 'responsabilidad', 'negative', 76),
('Falto a mis responsabilidades ocasionalmente', 'responsabilidad', 'negative', 77),
('Acepto trabajos de calidad mediocre', 'responsabilidad', 'negative', 78),
('Me distraigo fácilmente', 'responsabilidad', 'negative', 79),
('Actúo sin pensar en las consecuencias', 'responsabilidad', 'negative', 80),
('Preparo todo con anticipación', 'responsabilidad', 'positive', 81);

-- Completar Extraversión (25 preguntas total)
INSERT INTO public.personality_questions (question_text, ocean_factor, score_orientation, order_index) VALUES
-- Extraversión - facetas: Calidez, Gregarismo, Asertividad, Actividad, Búsqueda de emociones, Emociones positivas
('Hago amigos fácilmente', 'extraversion', 'positive', 82),
('Me gusta estar en multitudes', 'extraversion', 'positive', 83),
('Expreso mis opiniones con confianza', 'extraversion', 'positive', 84),
('Tengo mucha energía física', 'extraversion', 'positive', 85),
('Busco experiencias emocionantes', 'extraversion', 'positive', 86),
('Me río frecuentemente', 'extraversion', 'positive', 87),
('Evito las reuniones sociales', 'extraversion', 'negative', 88),
('Prefiero actividades silenciosas', 'extraversion', 'negative', 89),
('Me cuesta expresar mi opinión en grupos', 'extraversion', 'negative', 90),
('Prefiero un ritmo de vida tranquilo', 'extraversion', 'negative', 91),
('Evito situaciones estimulantes', 'extraversion', 'negative', 92),
('Rara vez me siento eufórico', 'extraversion', 'negative', 93),
('Soy el alma de las fiestas', 'extraversion', 'positive', 94),
('Disfruto conocer gente nueva', 'extraversion', 'positive', 95),
('Tomo la iniciativa en grupos', 'extraversion', 'positive', 96),
('Me mantengo activo todo el día', 'extraversion', 'positive', 97),
('Me gustan los deportes extremos', 'extraversion', 'positive', 98),
('Experimento alegría intensamente', 'extraversion', 'positive', 99),
('Me aíslo socialmente', 'extraversion', 'negative', 100),
('Soy tímido con extraños', 'extraversion', 'negative', 101),
('Evito ser el líder', 'extraversion', 'negative', 102),
('Me canso fácilmente', 'extraversion', 'negative', 103),
('Prefiero la seguridad a la aventura', 'extraversion', 'negative', 104),
('Tengo un temperamento serio', 'extraversion', 'negative', 105),
('Inicio conversaciones espontáneamente', 'extraversion', 'positive', 106);

-- Completar Amabilidad (25 preguntas total)
INSERT INTO public.personality_questions (question_text, ocean_factor, score_orientation, order_index) VALUES
-- Amabilidad - facetas: Confianza, Franqueza, Altruismo, Complacencia, Modestia, Sensibilidad moral
('Confío en las intenciones de otros', 'amabilidad', 'positive', 107),
('Soy honesto en mis relaciones', 'amabilidad', 'positive', 108),
('Ayudo sin esperar nada a cambio', 'amabilidad', 'positive', 109),
('Evito conflictos cuando es posible', 'amabilidad', 'positive', 110),
('No me gusta presumir mis logros', 'amabilidad', 'positive', 111),
('Me afectan los problemas de otros', 'amabilidad', 'positive', 112),
('Sospecho de las motivaciones ajenas', 'amabilidad', 'negative', 113),
('Oculto información para mi beneficio', 'amabilidad', 'negative', 114),
('Priorizo mis necesidades sobre las de otros', 'amabilidad', 'negative', 115),
('Disfruto discutir y debatir', 'amabilidad', 'negative', 116),
('Me gusta ser el centro de atención', 'amabilidad', 'negative', 117),
('Los problemas ajenos no me conciernen', 'amabilidad', 'negative', 118),
('Doy el beneficio de la duda', 'amabilidad', 'positive', 119),
('Admito mis errores abiertamente', 'amabilidad', 'positive', 120),
('Me sacrifico por el bienestar de otros', 'amabilidad', 'positive', 121),
('Busco soluciones ganar-ganar', 'amabilidad', 'positive', 122),
('Reconozco los méritos de otros', 'amabilidad', 'positive', 123),
('Siento empatía por los que sufren', 'amabilidad', 'positive', 124),
('Asumo que otros me van a engañar', 'amabilidad', 'negative', 125),
('Exagero mis cualidades', 'amabilidad', 'negative', 126),
('Busco mi beneficio personal primero', 'amabilidad', 'negative', 127),
('Me gusta ganar argumentos', 'amabilidad', 'negative', 128),
('Busco reconocimiento por mis acciones', 'amabilidad', 'negative', 129),
('Ignoro el sufrimiento ajeno', 'amabilidad', 'negative', 130),
('Creo en la bondad humana', 'amabilidad', 'positive', 131);

-- Completar Neuroticismo (25 preguntas total)
INSERT INTO public.personality_questions (question_text, ocean_factor, score_orientation, order_index) VALUES
-- Neuroticismo - facetas: Ansiedad, Hostilidad, Depresión, Ansiedad social, Impulsividad, Vulnerabilidad
('Me preocupo por cosas que podrían salir mal', 'neuroticismo', 'positive', 132),
('Me irrito fácilmente con otros', 'neuroticismo', 'positive', 133),
('A menudo me siento triste sin razón', 'neuroticismo', 'positive', 134),
('Me pongo nervioso en situaciones sociales', 'neuroticismo', 'positive', 135),
('Hago cosas de las que me arrepiento', 'neuroticismo', 'positive', 136),
('Me siento abrumado por el estrés', 'neuroticismo', 'positive', 137),
('Rara vez me preocupo por el futuro', 'neuroticismo', 'negative', 138),
('Mantengo la calma en conflictos', 'neuroticismo', 'negative', 139),
('Tengo un estado de ánimo estable', 'neuroticismo', 'negative', 140),
('Me siento cómodo en grupos grandes', 'neuroticismo', 'negative', 141),
('Pienso antes de hablar', 'neuroticismo', 'negative', 142),
('Manejo bien la presión', 'neuroticismo', 'negative', 143),
('Anticipo problemas constantemente', 'neuroticismo', 'positive', 144),
('Exploto de ira fácilmente', 'neuroticismo', 'positive', 145),
('Experimento bajones emocionales', 'neuroticismo', 'positive', 146),
('Evito hablar en público', 'neuroticismo', 'positive', 147),
('Digo cosas sin pensar', 'neuroticismo', 'positive', 148),
('Las crisis me paralizan', 'neuroticismo', 'positive', 149),
('Tengo una perspectiva optimista', 'neuroticismo', 'negative', 150),
('Soy paciente con otros', 'neuroticismo', 'negative', 151),
('Me recupero rápido de decepciones', 'neuroticismo', 'negative', 152),
('Disfruto conocer gente nueva', 'neuroticismo', 'negative', 153),
('Controlo mis reacciones emocionales', 'neuroticismo', 'negative', 154),
('Resuelvo problemas efectivamente', 'neuroticismo', 'negative', 155),
('Duermo mal cuando estoy preocupado', 'neuroticismo', 'positive', 156);