// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://popufimnleaubvlwyusb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcHVmaW1ubGVhdWJ2bHd5dXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTI3MjEsImV4cCI6MjA2NTAyODcyMX0.7_SpiarJ0nibmxciG8464R7pmGhOgAQvMFDn2lgQuEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);